name: Task Prioritizer DockerHub Push

on: push: branches: [ main ]

jobs: build-and-publish: name: Build and Publish Docker Image runs-on: self-hosted steps: - uses: actions/checkout@v3

- name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Docker metadata
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: ${{ secrets.DOCKERHUB_USERNAME }}/task-prioritizer
      tags: |
        type=sha,format=short
        type=ref,event=branch
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,value=latest,enable={{is_default_branch}}

  - name: Build and push
    uses: docker/build-push-action@v4
    with:
      context: .
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

